# Generated by Django 5.2.16 on 2026-09-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="fulfillment_status",
            field=models.CharField(
                choices=[("pending", "Aguardando envio"), ("shipped", "Enviado")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="stores.store",
            ),
        ),
    ]
