# Generated by Django 5.2.16 on 2026-09-27 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="nome"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parceiros",
                    ),
                ),
            ],
            options={
                "verbose_name": "loja",
                "verbose_name_plural": "lojas",
                "ordering": ["name"],
            },
        ),
    ]
