# Generated by Django 5.2.16 on 2026-09-27 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_store"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="endereço (slug)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "accent_color",
                    models.CharField(
                        default="#795b3d",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use o formato #RRGGBB."
                            )
                        ],
                        verbose_name="cor de destaque",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="início"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fim"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="catalog.product",
                        verbose_name="produtos",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="stores.store",
                        verbose_name="loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "vitrine",
                "verbose_name_plural": "vitrines",
                "ordering": ["store__name", "name"],
            },
        ),
    ]
